# Generated by Django 4.0.4 on 2022-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'permissions': (('Operator', 'Can report malfunction'),),
            },
        ),
    ]
