# Generated by Django 4.0.4 on 2022-04-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'permissions': [('Operator', 'Can report malfunction')]},
        ),
    ]
