# Generated by Django 4.0.4 on 2022-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_setting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='malfunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
