# Generated by Django 4.0.4 on 2022-05-02 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='malfunction',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
