# Generated by Django 4.0.4 on 2022-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_malfunction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunction',
            name='responsible_person',
            field=models.CharField(default='', max_length=50),
        ),
    ]
